id = "hledger"
name = "hledger"
version = "0.0.1"
schema_version = 1
authors = ["Ramil Muratov <rmuratov@gmail.com>"]
description = "hledger language support for Zed"
repository = "https://github.com/rmuratov/hledger-zed"

[grammars.hledger]
repository = "https://github.com/rmuratov/tree-sitter-hledger"
rev = "3dfbbe25fa5d4d87119572a25ef1500335a4ccfb"
